/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => WebdavSyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  webdavUrl: "",
  username: "",
  password: "",
  syncOnSave: false,
  syncOnStartup: false,
  syncInterval: 0,
  syncDirection: "bidirectional",
  includePatterns: "",
  excludePatterns: ""
};
var PLUGIN_DATA_DIR = ".obsidian/plugins/obsidian-webdav-sync";
var STATE_FILE = "file-states.json";

// src/utils.ts
function parsePropfindResponse(xmlText, basePath) {
  const parser = new DOMParser();
  const xml = parser.parseFromString(xmlText, "application/xml");
  const parseError = xml.querySelector("parsererror");
  if (parseError) {
    throw new Error("XML \u89E3\u6790\u5931\u8D25: " + parseError.textContent);
  }
  const results = [];
  const responses = xml.querySelectorAll("D\\:response, response");
  responses.forEach((response) => {
    const hrefEl = response.querySelector("D\\:href, href");
    if (!hrefEl || !hrefEl.textContent)
      return;
    let href = hrefEl.textContent;
    try {
      href = decodeURIComponent(href);
    } catch {
    }
    if (href === basePath || href === basePath + "/")
      return;
    let relPath = href;
    if (basePath !== "/" && basePath !== "") {
      if (relPath.startsWith(basePath)) {
        relPath = relPath.slice(basePath.length);
      }
    }
    relPath = relPath.replace(/^\/+/, "").replace(/\/+$/, "");
    if (!relPath)
      return;
    const isDir = href.endsWith("/");
    const mtimeEl = response.querySelector("D\\:getlastmodified, getlastmodified");
    let mtime = null;
    if (mtimeEl && mtimeEl.textContent) {
      const parsed = Date.parse(mtimeEl.textContent);
      if (!isNaN(parsed))
        mtime = parsed;
    }
    const etagEl = response.querySelector("D\\:getetag, getetag");
    const etag = etagEl && etagEl.textContent ? etagEl.textContent.replace(/"/g, "") : null;
    results.push({
      path: relPath,
      mtime,
      etag,
      isDirectory: isDir
    });
  });
  return results.filter(
    (f) => f.path !== "" && f.path !== "/" && !(f.isDirectory && f.path === ".")
  );
}
async function computeHash(content) {
  const encoder = new TextEncoder();
  const data = encoder.encode(content);
  const hashBuffer = await crypto.subtle.digest("SHA-256", data);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  const hashHex = hashArray.map((b) => b.toString(16).padStart(2, "0")).join("");
  return hashHex.substring(0, 16);
}
function normalizePath(p) {
  return p.replace(/\\/g, "/").replace(/\/+/g, "/").replace(/^\/+/, "").replace(/\/+$/, "");
}
function matchGlob(pattern, filePath) {
  const normalizedPattern = normalizePath(pattern);
  const normalizedPath = normalizePath(filePath);
  let regexStr = "";
  let i = 0;
  while (i < normalizedPattern.length) {
    const ch = normalizedPattern[i];
    if (ch === "*" && normalizedPattern[i + 1] === "*" && normalizedPattern[i + 2] === "/") {
      regexStr += "(.*/)?";
      i += 3;
      continue;
    } else if (ch === "*" && normalizedPattern[i + 1] === "*" && normalizedPattern[i + 2] === void 0) {
      regexStr += ".*";
      i += 2;
      continue;
    } else if (ch === "*" && normalizedPattern[i + 1] === "/") {
      regexStr += "[^/]+/";
      i += 2;
      continue;
    } else if (ch === "*") {
      regexStr += "[^/]*";
      i += 1;
      continue;
    } else if (ch === "?") {
      regexStr += "[^/]";
      i += 1;
      continue;
    } else if (ch === "{") {
      const closeBrace = normalizedPattern.indexOf("}", i);
      if (closeBrace !== -1) {
        const alternatives = normalizedPattern.substring(i + 1, closeBrace).split(",");
        regexStr += "(" + alternatives.map((a) => a.trim().replace(/[.*+?^${}()|[\]\\]/g, "\\$&")).join("|") + ")";
        i = closeBrace + 1;
        continue;
      }
    } else if (/[.+?^${}()|[\]\\]/.test(ch)) {
      regexStr += "\\" + ch;
    } else {
      regexStr += ch;
    }
    i++;
  }
  try {
    const regex = new RegExp("^" + regexStr + "$");
    return regex.test(normalizedPath);
  } catch {
    return normalizedPath.startsWith(normalizedPattern);
  }
}
function formatTimestamp(date) {
  const pad = (n, len = 2) => n.toString().padStart(len, "0");
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}_${pad(date.getHours())}${pad(date.getMinutes())}${pad(date.getSeconds())}`;
}
function getBackupPath(originalPath) {
  const dir = originalPath.includes("/") ? originalPath.substring(0, originalPath.lastIndexOf("/") + 1) : "";
  const filename = originalPath.includes("/") ? originalPath.substring(originalPath.lastIndexOf("/") + 1) : originalPath;
  const lastDot = filename.lastIndexOf(".");
  if (lastDot <= 0) {
    return `${dir}${filename}.${formatTimestamp(new Date())}`;
  }
  const basename = filename.substring(0, lastDot);
  const ext = filename.substring(lastDot);
  return `${dir}${basename}.${formatTimestamp(new Date())}${ext}`;
}
function isObsidianDir(path) {
  return path.startsWith(".obsidian/") || path === ".obsidian";
}
function shouldExclude(path, excludePatterns, includePatterns) {
  if (isObsidianDir(path))
    return true;
  if (includePatterns.length > 0) {
    const matchesInclude = includePatterns.some((p) => matchGlob(p.trim(), path));
    if (!matchesInclude)
      return true;
  }
  if (excludePatterns.length > 0) {
    return excludePatterns.some((p) => p.trim() && matchGlob(p.trim(), path));
  }
  return false;
}

// src/webdav-client.ts
var WebdavClient = class {
  constructor(baseUrl, username, password) {
    this.baseUrl = baseUrl.endsWith("/") ? baseUrl : baseUrl + "/";
    const credentials = btoa(`${username}:${password}`);
    this.headers = {
      Authorization: `Basic ${credentials}`
    };
  }
  /**
   * 获取基础 URL
   */
  getUrl() {
    return this.baseUrl;
  }
  /**
   * 构建完整 URL（拼接路径）
   * 对路径中的中文和特殊字符做 URL 编码
   */
  buildUrl(path) {
    const cleanPath = path.replace(/^\/+/, "").replace(/\/+$/, "");
    const encoded = cleanPath.split("/").map((seg) => encodeURIComponent(seg)).join("/");
    return this.baseUrl + encoded;
  }
  /**
   * 发起 fetch 请求的通用方法
   */
  async request(path, options = {}, retries = 3) {
    const url = this.buildUrl(path);
    let lastError = null;
    for (let attempt = 0; attempt < retries; attempt++) {
      try {
        const response = await fetch(url, {
          ...options,
          headers: {
            ...this.headers,
            ...options.headers || {}
          }
        });
        return response;
      } catch (err) {
        lastError = err instanceof Error ? err : new Error(String(err));
        if (attempt < retries - 1) {
          await new Promise((r) => setTimeout(r, 1e3 * Math.pow(2, attempt)));
        }
      }
    }
    throw lastError || new Error(`\u8BF7\u6C42\u5931\u8D25: ${path}`);
  }
  /**
   * PROPFIND — 列出目录内容
   */
  async list(path = "") {
    const response = await this.request(path, {
      method: "PROPFIND",
      headers: {
        Depth: "1",
        Accept: "application/xml"
      }
    });
    if (!response.ok) {
      throw new Error(`PROPFIND \u5931\u8D25: ${response.status} ${response.statusText}`);
    }
    const xmlText = await response.text();
    return parsePropfindResponse(xmlText, path);
  }
  /**
   * 递归列出所有文件和目录
   */
  async listRecursive(path = "") {
    const allFiles = [];
    const queue = [path];
    while (queue.length > 0) {
      const current = queue.shift();
      const items = await this.list(current);
      for (const item of items) {
        if (item.path === current || item.path === "")
          continue;
        allFiles.push(item);
        if (item.isDirectory) {
          queue.push(item.path);
        }
      }
    }
    return allFiles;
  }
  /**
   * GET — 下载文件内容
   */
  async download(path) {
    const response = await this.request(path, {
      method: "GET"
    });
    if (!response.ok) {
      throw new Error(`GET \u5931\u8D25: ${response.status} ${response.statusText}`);
    }
    return await response.text();
  }
  /**
   * PUT — 上传文件内容
   */
  async upload(path, content) {
    const response = await this.request(path, {
      method: "PUT",
      body: content,
      headers: {
        "Content-Type": "application/octet-stream"
      }
    });
    if (!response.ok) {
      throw new Error(`PUT \u5931\u8D25: ${response.status} ${response.statusText}`);
    }
    return response.headers.get("ETag");
  }
  /**
   * DELETE — 删除文件或目录
   */
  async delete(path) {
    const response = await this.request(path, {
      method: "DELETE"
    });
    if (!response.ok && response.status !== 404) {
      throw new Error(`DELETE \u5931\u8D25: ${response.status} ${response.statusText}`);
    }
  }
  /**
   * MKCOL — 创建目录
   */
  async createDirectory(path) {
    const response = await this.request(path, {
      method: "MKCOL"
    });
    if (!response.ok && response.status !== 405) {
      throw new Error(`MKCOL \u5931\u8D25: ${response.status} ${response.statusText}`);
    }
  }
  /**
   * MOVE — 重命名/移动文件
   */
  async move(from, to) {
    const destinationUrl = this.buildUrl(to);
    const response = await this.request(from, {
      method: "MOVE",
      headers: {
        Destination: destinationUrl
      }
    });
    if (!response.ok) {
      throw new Error(`MOVE \u5931\u8D25: ${response.status} ${response.statusText}`);
    }
  }
  /**
   * 确保远程目录存在（递归创建）
   */
  async ensureDirectory(dirPath) {
    const parts = dirPath.split("/").filter(Boolean);
    let current = "";
    for (const part of parts) {
      current += part + "/";
      try {
        await this.createDirectory(current);
      } catch (err) {
        if (err instanceof Error && err.message.includes("405")) {
          continue;
        }
        throw err;
      }
    }
  }
  /**
   * 测试连接 — 向根路径发送 PROPFIND
   */
  async testConnection() {
    try {
      await this.list("");
      return { ok: true, message: "\u8FDE\u63A5\u6210\u529F" };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return { ok: false, message: msg };
    }
  }
};

// src/file-tracker.ts
var FileTracker = class {
  constructor(vault) {
    this.states = /* @__PURE__ */ new Map();
    this.loaded = false;
    this.vault = vault;
    this.pluginDir = PLUGIN_DATA_DIR;
  }
  /**
   * 获取状态文件完整路径
   */
  getStateFilePath() {
    return `${this.pluginDir}/${STATE_FILE}`;
  }
  /**
   * 从 vault 加载状态文件
   */
  async load() {
    try {
      const filePath = this.getStateFilePath();
      const exists = await this.vault.adapter.exists(filePath);
      if (!exists) {
        this.loaded = true;
        return;
      }
      const content = await this.vault.adapter.read(filePath);
      const data = JSON.parse(content);
      this.states.clear();
      for (const state of data) {
        const decodedPath = decodeURIComponent(state.path);
        state.path = decodedPath;
        this.states.set(normalizePath(decodedPath), state);
      }
    } catch (err) {
      console.error("\u52A0\u8F7D\u6587\u4EF6\u72B6\u6001\u5931\u8D25:", err);
      this.states.clear();
    }
    this.loaded = true;
  }
  /**
   * 保存状态文件到 vault
   */
  async save() {
    try {
      await this.vault.adapter.mkdir(this.pluginDir);
      const data = Array.from(this.states.values());
      await this.vault.adapter.write(
        this.getStateFilePath(),
        JSON.stringify(data, null, 2)
      );
    } catch (err) {
      console.error("\u4FDD\u5B58\u6587\u4EF6\u72B6\u6001\u5931\u8D25:", err);
    }
  }
  /**
   * 获取单个文件状态
   */
  getState(path) {
    return this.states.get(normalizePath(path));
  }
  /**
   * 设置单个文件状态
   */
  setState(path, state) {
    const key = normalizePath(path);
    const existing = this.states.get(key) || {
      path: key,
      localMtime: 0,
      localHash: "",
      remoteMtime: null,
      remoteHash: null,
      status: "synced"
    };
    this.states.set(key, { ...existing, ...state, path: key });
  }
  /**
   * 删除文件状态
   */
  removeState(path) {
    this.states.delete(normalizePath(path));
  }
  /**
   * 获取所有跟踪的文件路径
   */
  getAllPaths() {
    return Array.from(this.states.keys());
  }
  /**
   * 扫描本地文件，返回文件信息列表
   */
  async scanLocal() {
    const files = [];
    const allFiles = this.vault.getFiles();
    for (const file of allFiles) {
      if (file.path.startsWith(".obsidian/"))
        continue;
      try {
        const content = await this.vault.read(file);
        const hash = await computeHash(content);
        files.push({
          path: file.path,
          mtime: file.stat.mtime,
          hash
        });
      } catch (err) {
        console.warn(`\u8BFB\u53D6\u6587\u4EF6\u5931\u8D25 ${file.path}:`, err);
      }
    }
    return files;
  }
  /**
   * 计算本地文件信息（用于单文件同步）
   */
  async getLocalFileInfo(file) {
    try {
      const content = await this.vault.read(file);
      const hash = await computeHash(content);
      return {
        path: file.path,
        mtime: file.stat.mtime,
        hash
      };
    } catch {
      return null;
    }
  }
  /**
   * 对比本地文件和远程文件，生成同步操作列表
   *
   * 返回:
   *  - upload: 仅本地有 或 本地有修改但远程未变
   *  - download: 仅远程有 或 远程有修改但本地未变
   *  - conflict: 双方都有修改
   *  - synced: 双方一致（跳过）
   */
  compare(localFiles, remoteFiles) {
    const localMap = /* @__PURE__ */ new Map();
    for (const f of localFiles) {
      localMap.set(normalizePath(f.path), f);
    }
    const remoteMap = /* @__PURE__ */ new Map();
    for (const f of remoteFiles) {
      if (!f.isDirectory) {
        remoteMap.set(normalizePath(f.path), f);
      }
    }
    const uploadPaths = [];
    const downloadPaths = [];
    const localCount = localMap.size;
    const remoteCount = remoteMap.size;
    const expectedCount = this.states.size;
    const canAssumeDelete = expectedCount === 0 || localCount >= expectedCount * 0.5 && remoteCount >= expectedCount * 0.5;
    const conflictPaths = [];
    const deleteRemotePaths = [];
    const deleteLocalPaths = [];
    const syncedPaths = [];
    for (const [localPath, localInfo] of localMap) {
      const remoteInfo = remoteMap.get(localPath);
      const savedState = this.states.get(localPath);
      if (!remoteInfo) {
        uploadPaths.push(localPath);
      } else {
        if (!savedState) {
          syncedPaths.push(localPath);
          continue;
        }
        const localChanged = savedState.localHash !== localInfo.hash || savedState.localMtime !== localInfo.mtime;
        const remoteChanged = !savedState.remoteHash || remoteInfo.etag && savedState.remoteHash !== remoteInfo.etag || savedState.remoteMtime !== null && remoteInfo.mtime !== null && savedState.remoteMtime !== remoteInfo.mtime;
        if (!localChanged && !remoteChanged) {
          syncedPaths.push(localPath);
        } else if (localChanged && !remoteChanged) {
          uploadPaths.push(localPath);
        } else if (!localChanged && remoteChanged) {
          downloadPaths.push(localPath);
        } else {
          conflictPaths.push(localPath);
        }
      }
    }
    for (const [remotePath, remoteInfo] of remoteMap) {
      if (!localMap.has(remotePath)) {
        const savedState = this.states.get(remotePath);
        if (savedState && savedState.localHash && canAssumeDelete) {
          deleteRemotePaths.push(remotePath);
        } else {
          downloadPaths.push(remotePath);
        }
      }
    }
    if (canAssumeDelete) {
      for (const [path, state] of this.states) {
        if (state.status === "synced" && !localMap.has(path) && remoteMap.has(path)) {
          if (!deleteRemotePaths.includes(path)) {
            deleteRemotePaths.push(path);
          }
        }
      }
    }
    if (canAssumeDelete) {
      for (const [path, state] of this.states) {
        if (state.status === "synced" && localMap.has(path) && !remoteMap.has(path)) {
          if (!deleteLocalPaths.includes(path)) {
            deleteLocalPaths.push(path);
          }
        }
      }
    }
    return {
      uploadPaths: [...new Set(uploadPaths)],
      downloadPaths: [...new Set(downloadPaths)],
      conflictPaths: [...new Set(conflictPaths)],
      deleteRemotePaths: [...new Set(deleteRemotePaths)],
      deleteLocalPaths: [...new Set(deleteLocalPaths)],
      syncedPaths: [...new Set(syncedPaths)]
    };
  }
  /**
   * 是否已加载状态文件
   */
  isLoaded() {
    return this.loaded;
  }
};

// src/conflict-resolver.ts
var ConflictResolver = class {
  constructor(vault, client) {
    this.vault = vault;
    this.client = client;
  }
  /**
   * 处理冲突文件列表，返回具体的 sync actions
   *
   * @param conflictPaths 冲突文件路径列表
   * @param localMtimes 本地 mtime 映射
   * @param remoteMtimes 远程 mtime 映射
   */
  async resolve(conflictPaths, localTimes, remoteTimes, localContents) {
    const actions = [];
    for (const path of conflictPaths) {
      const localMtime = localTimes.get(path) || 0;
      const remoteMtime = remoteTimes.get(path) || 0;
      if (localMtime >= remoteMtime) {
        const backupPath = getBackupPath(path);
        actions.push({
          type: "conflict_upload",
          path,
          backupPath,
          content: localContents.get(path)
        });
      } else {
        const backupPath = getBackupPath(path);
        actions.push({
          type: "conflict_download",
          path,
          backupPath
        });
      }
    }
    return actions;
  }
  /**
   * 执行冲突上传：MOVE 远程旧文件 → PUT 新文件
   */
  async executeConflictUpload(path, backupPath, content) {
    const dir = path.includes("/") ? path.substring(0, path.lastIndexOf("/")) : "";
    const fullBackupPath = dir ? `${dir}/${backupPath.replace(/^.*\//, "")}` : backupPath;
    if (content === void 0) {
      console.warn(`\u51B2\u7A81\u4E0A\u4F20\u8DF3\u8FC7 ${path}: \u672C\u5730\u6587\u4EF6\u5185\u5BB9\u4E0D\u53EF\u8BFB`);
      return;
    }
    try {
      await this.client.move(path, fullBackupPath);
    } catch (err) {
      console.warn(`\u8FDC\u7A0B\u5907\u4EFD\u5931\u8D25 ${path} \u2192 ${fullBackupPath}:`, err);
    }
    const dirPath = path.includes("/") ? path.substring(0, path.lastIndexOf("/")) : "";
    if (dirPath) {
      await this.client.ensureDirectory(dirPath);
    }
    await this.client.upload(path, content);
  }
  /**
   * 执行冲突下载：本地旧文件改名 → GET 远程新文件
   */
  async executeConflictDownload(path, backupPath) {
    try {
      const dir = path.includes("/") ? path.substring(0, path.lastIndexOf("/")) : "";
      const fullBackupPath = dir ? `${dir}/${backupPath.replace(/^.*\//, "")}` : backupPath;
      await this.vault.rename(
        this.vault.getAbstractFileByPath(path),
        fullBackupPath
      );
    } catch (err) {
      console.warn(`\u672C\u5730\u5907\u4EFD\u5931\u8D25 ${path} \u2192 ${backupPath}:`, err);
    }
    try {
      const content = await this.client.download(path);
      const dirPath = path.includes("/") ? path.substring(0, path.lastIndexOf("/")) : "";
      if (dirPath) {
        await this.vault.adapter.mkdir(dirPath);
      }
      await this.vault.adapter.write(path, content);
    } catch (err) {
      console.warn(`\u4E0B\u8F7D\u51B2\u7A81\u6587\u4EF6\u5931\u8D25 ${path}:`, err);
    }
  }
};

// src/sync-engine.ts
var import_obsidian = require("obsidian");
var SyncEngine = class {
  constructor(vault, client, tracker, resolver, settings, logger) {
    this.abortFlag = false;
    this.syncing = false;
    this.onProgress = null;
    this.vault = vault;
    this.client = client;
    this.tracker = tracker;
    this.resolver = resolver;
    this.settings = settings;
    this.logger = logger;
  }
  /**
   * 设置进度回调
   */
  setOnProgress(callback) {
    this.onProgress = callback;
  }
  /**
   * 是否正在同步
   */
  isSyncing() {
    return this.syncing;
  }
  /**
   * 中止同步
   */
  abort() {
    this.abortFlag = true;
  }
  /**
   * 报告进度
   */
  reportProgress(current, total, message) {
    if (this.onProgress) {
      this.onProgress(current, total, message);
    }
  }
  /**
   * 执行完整同步流程
   */
  async sync() {
    if (this.syncing) {
      return { success: false, message: "\u540C\u6B65\u5DF2\u5728\u8FDB\u884C\u4E2D", actions: [] };
    }
    this.syncing = true;
    this.abortFlag = false;
    const actions = [];
    let uploaded = 0, downloaded = 0, deletedRemote = 0, deletedLocal = 0, conflicted = 0;
    try {
      this.reportProgress(0, 100, "\u626B\u63CF\u672C\u5730\u6587\u4EF6...");
      const localFiles = await this.scanLocal();
      if (this.abortFlag)
        throw new Error("\u540C\u6B65\u5DF2\u4E2D\u6B62");
      this.reportProgress(0, 100, "\u5217\u51FA\u8FDC\u7A0B\u6587\u4EF6...");
      const remoteFiles = await this.listRemote();
      if (this.abortFlag)
        throw new Error("\u540C\u6B65\u5DF2\u4E2D\u6B62");
      this.reportProgress(0, 100, "\u5BF9\u6BD4\u6587\u4EF6\u53D8\u66F4...");
      const excludePatterns = (this.settings.excludePatterns || "").split("\n").filter((p) => p.trim());
      const includePatterns = (this.settings.includePatterns || "").split("\n").filter((p) => p.trim());
      for (const path of this.tracker.getAllPaths()) {
        if (shouldExclude(path, excludePatterns, includePatterns)) {
          this.tracker.removeState(path);
        }
      }
      const comparison = this.tracker.compare(localFiles, remoteFiles);
      if (this.abortFlag)
        throw new Error("\u540C\u6B65\u5DF2\u4E2D\u6B62");
      const direction = this.settings.syncDirection;
      let {
        uploadPaths,
        downloadPaths,
        conflictPaths,
        deleteRemotePaths,
        deleteLocalPaths
      } = comparison;
      if (direction === "upload_only") {
        downloadPaths = [];
        deleteLocalPaths = [];
        conflictPaths = [];
      } else if (direction === "download_only") {
        uploadPaths = [];
        deleteRemotePaths = [];
        conflictPaths = [];
      }
      if (conflictPaths.length > 0) {
        this.reportProgress(0, 100, `\u5904\u7406 ${conflictPaths.length} \u4E2A\u51B2\u7A81\u6587\u4EF6...`);
        const localMap = new Map(localFiles.map((f) => [f.path, f]));
        const remoteMap = new Map(remoteFiles.map((f) => [f.path, f]));
        const localTimes = /* @__PURE__ */ new Map();
        const remoteTimes = /* @__PURE__ */ new Map();
        const localContents = /* @__PURE__ */ new Map();
        for (const p of conflictPaths) {
          const lf = localMap.get(p);
          const rf = remoteMap.get(p);
          if (lf)
            localTimes.set(p, lf.mtime);
          if (rf && rf.mtime)
            remoteTimes.set(p, rf.mtime);
          if (lf) {
            try {
              const content = await this.vault.adapter.read(p);
              localContents.set(p, content);
            } catch {
              this.logger.warn(`\u8BFB\u53D6\u51B2\u7A81\u6587\u4EF6\u5185\u5BB9\u5931\u8D25: ${p}`);
            }
          }
        }
        const conflictActions = await this.resolver.resolve(
          conflictPaths,
          localTimes,
          remoteTimes,
          localContents
        );
        actions.push(...conflictActions);
        if (this.abortFlag)
          throw new Error("\u540C\u6B65\u5DF2\u4E2D\u6B62");
      }
      const totalActions = uploadPaths.length + downloadPaths.length + deleteRemotePaths.length + deleteLocalPaths.length + actions.length;
      if (totalActions === 0) {
        this.reportProgress(100, 100, "\u6240\u6709\u6587\u4EF6\u5DF2\u540C\u6B65");
        this.syncing = false;
        return { success: true, message: "\u6240\u6709\u6587\u4EF6\u5DF2\u662F\u6700\u65B0", actions: [] };
      }
      const result = await this.executeActions(
        uploadPaths,
        downloadPaths,
        deleteRemotePaths,
        deleteLocalPaths,
        actions,
        localFiles
      );
      await this.updateStates(
        uploadPaths,
        downloadPaths,
        deleteRemotePaths,
        deleteLocalPaths,
        conflictPaths,
        localFiles,
        remoteFiles,
        result.postUploadEtags,
        result.postDownloadMtimes
      );
      if (uploadPaths.length > 0 || downloadPaths.length > 0 || conflictPaths.length > 0) {
        this.reportProgress(0, 0, "\u5237\u65B0\u8FDC\u7A0B\u6587\u4EF6\u72B6\u6001...");
        try {
          const freshRemote = await this.listRemote();
          const freshMap = new Map(freshRemote.map((f) => [f.path, f]));
          for (const path of [...uploadPaths, ...downloadPaths, ...conflictPaths]) {
            const fresh = freshMap.get(path);
            if (fresh) {
              this.tracker.setState(path, {
                remoteMtime: fresh.mtime,
                remoteHash: fresh.etag,
                status: "synced"
              });
            }
          }
        } catch (err) {
          this.logger.warn(`\u5237\u65B0\u8FDC\u7A0B\u72B6\u6001\u5931\u8D25: ${err}`);
        }
      }
      await this.tracker.save();
      this.syncing = false;
      return {
        success: true,
        message: `\u540C\u6B65\u5B8C\u6210: \u2191${uploadPaths.length} \u4E0A\u4F20, \u2193${downloadPaths.length} \u4E0B\u8F7D, \u26A0${conflictPaths.length} \u51B2\u7A81, \u2715${deleteRemotePaths.length + deleteLocalPaths.length} \u5220\u9664`,
        actions
      };
    } catch (err) {
      this.syncing = false;
      const msg = err instanceof Error ? err.message : String(err);
      return { success: false, message: msg, actions };
    }
  }
  /**
   * 扫描本地文件
   */
  async scanLocal() {
    const allFiles = this.vault.getFiles();
    const result = [];
    const includePatterns = (this.settings.includePatterns || "").split("\n").filter((p) => p.trim());
    const excludePatterns = (this.settings.excludePatterns || "").split("\n").filter((p) => p.trim());
    for (let i = 0; i < allFiles.length; i++) {
      if (this.abortFlag)
        throw new Error("\u540C\u6B65\u5DF2\u4E2D\u6B62");
      const file = allFiles[i];
      if (shouldExclude(file.path, excludePatterns, includePatterns))
        continue;
      this.reportProgress(i, allFiles.length, `\u626B\u63CF: ${file.path}`);
      try {
        const content = await this.vault.read(file);
        const hash = await computeHash(content);
        result.push({
          path: file.path,
          mtime: file.stat.mtime,
          hash
        });
      } catch (err) {
        this.logger.warn(`\u8BFB\u53D6\u6587\u4EF6\u5931\u8D25 ${file.path}: ${err}`);
      }
    }
    return result;
  }
  /**
   * 列出远程文件
   */
  async listRemote() {
    try {
      return await this.client.listRecursive();
    } catch (err) {
      console.warn("\u9012\u5F52\u5217\u51FA\u8FDC\u7A0B\u6587\u4EF6\u5931\u8D25\uFF0C\u5C1D\u8BD5\u5355\u5C42:", err);
      return await this.client.list();
    }
  }
  /**
   * 执行同步操作
   */
  async executeActions(uploadPaths, downloadPaths, deleteRemotePaths, deleteLocalPaths, conflictActions, localFiles) {
    const total = uploadPaths.length + downloadPaths.length + deleteRemotePaths.length + deleteLocalPaths.length + conflictActions.length;
    let completed = 0;
    const errors = [];
    const postUploadEtags = /* @__PURE__ */ new Map();
    const postDownloadMtimes = /* @__PURE__ */ new Map();
    const allDirs = /* @__PURE__ */ new Set();
    for (const p of [...uploadPaths, ...conflictActions.map((a) => a.path)]) {
      if (p.includes("/")) {
        allDirs.add(p.substring(0, p.lastIndexOf("/")));
      }
    }
    const sortedDirs = [...allDirs].sort((a, b) => a.split("/").length - b.split("/").length);
    for (const dir of sortedDirs) {
      if (this.abortFlag)
        throw new Error("\u540C\u6B65\u5DF2\u4E2D\u6B62");
      try {
        await this.client.ensureDirectory(dir);
      } catch (err) {
        errors.push(`\u521B\u5EFA\u8FDC\u7A0B\u76EE\u5F55\u5931\u8D25 ${dir}: ${err}`);
        this.logger.warn(`\u521B\u5EFA\u8FDC\u7A0B\u76EE\u5F55\u5931\u8D25 ${dir}: ${err}`);
      }
    }
    if (this.abortFlag)
      throw new Error("\u540C\u6B65\u5DF2\u4E2D\u6B62");
    for (const p of downloadPaths) {
      if (p.includes("/")) {
        const dir = p.substring(0, p.lastIndexOf("/"));
        await this.vault.adapter.mkdir(dir);
      }
    }
    for (const path of uploadPaths) {
      if (this.abortFlag)
        throw new Error("\u540C\u6B65\u5DF2\u4E2D\u6B62");
      this.reportProgress(completed, total, `\u2191 \u4E0A\u4F20: ${path}`);
      try {
        const content = await this.vault.adapter.read(path);
        this.logger.info(`\u2191 \u4E0A\u4F20: ${path}`);
        const etag = await this.client.upload(path, content);
        postUploadEtags.set(path, etag);
      } catch (err) {
        errors.push(`\u2191 \u4E0A\u4F20\u5931\u8D25 ${path}: ${err}`);
        this.logger.error(`\u2191 \u4E0A\u4F20\u5931\u8D25 ${path}: ${err}`);
      }
      completed++;
    }
    for (const path of downloadPaths) {
      if (this.abortFlag)
        throw new Error("\u540C\u6B65\u5DF2\u4E2D\u6B62");
      this.reportProgress(completed, total, `\u2193 \u4E0B\u8F7D: ${path}`);
      try {
        const content = await this.client.download(path);
        this.logger.info(`\u2193 \u4E0B\u8F7D: ${path}`);
        if (content !== void 0) {
          await this.vault.adapter.write(path, content);
          const file = this.vault.getAbstractFileByPath(path);
          if (file && "stat" in file) {
            postDownloadMtimes.set(path, file.stat.mtime);
          }
        }
      } catch (err) {
        errors.push(`\u2193 \u4E0B\u8F7D\u5931\u8D25 ${path}: ${err}`);
        this.logger.error(`\u2193 \u4E0B\u8F7D\u5931\u8D25 ${path}: ${err}`);
      }
      completed++;
    }
    for (const path of deleteRemotePaths) {
      if (this.abortFlag)
        throw new Error("\u540C\u6B65\u5DF2\u4E2D\u6B62");
      this.reportProgress(completed, total, `\u2715 \u5220\u9664\u8FDC\u7A0B: ${path}`);
      try {
        await this.client.delete(path);
        this.logger.info(`\u2715 \u5220\u9664\u8FDC\u7A0B: ${path}`);
      } catch (err) {
        errors.push(`\u2715 \u5220\u9664\u8FDC\u7A0B\u5931\u8D25 ${path}: ${err}`);
        this.logger.error(`\u2715 \u5220\u9664\u8FDC\u7A0B\u5931\u8D25 ${path}: ${err}`);
      }
      completed++;
    }
    for (const path of deleteLocalPaths) {
      if (this.abortFlag)
        throw new Error("\u540C\u6B65\u5DF2\u4E2D\u6B62");
      this.reportProgress(completed, total, `\u2715 \u5220\u9664\u672C\u5730: ${path}`);
      try {
        const decodedPath = decodeURIComponent(path);
        const file = this.vault.getAbstractFileByPath(decodedPath);
        if (file) {
          await this.vault.delete(file);
        }
        this.logger.info(`\u2715 \u5220\u9664\u672C\u5730: ${path}`);
      } catch (err) {
        errors.push(`\u2715 \u5220\u9664\u672C\u5730\u5931\u8D25 ${path}: ${err}`);
        this.logger.error(`\u2715 \u5220\u9664\u672C\u5730\u5931\u8D25 ${path}: ${err}`);
      }
      completed++;
    }
    for (const action of conflictActions) {
      if (this.abortFlag)
        throw new Error("\u540C\u6B65\u5DF2\u4E2D\u6B62");
      this.reportProgress(completed, total, `\u26A0 \u5904\u7406\u51B2\u7A81: ${action.path}`);
      try {
        if (action.type === "conflict_upload") {
          this.logger.warn(`\u26A0 \u51B2\u7A81\u4E0A\u4F20 ${action.path} \u2192 \u8FDC\u7A0B\u65E7\u6587\u4EF6\u5907\u4EFD\u4E3A ${action.backupPath}`);
          await this.resolver.executeConflictUpload(
            action.path,
            action.backupPath,
            action.content
          );
        } else if (action.type === "conflict_download") {
          this.logger.warn(`\u26A0 \u51B2\u7A81\u4E0B\u8F7D ${action.path} \u2192 \u672C\u5730\u65E7\u6587\u4EF6\u5907\u4EFD\u4E3A ${action.backupPath}`);
          await this.resolver.executeConflictDownload(action.path, action.backupPath);
        }
      } catch (err) {
        errors.push(`\u26A0 \u51B2\u7A81\u5904\u7406\u5931\u8D25 ${action.path}: ${err}`);
        this.logger.error(`\u26A0 \u51B2\u7A81\u5904\u7406\u5931\u8D25 ${action.path}: ${err}`);
      }
      completed++;
    }
    if (errors.length > 0) {
      this.logger.error(`\u540C\u6B65\u5B8C\u6210\uFF0C\u5171 ${errors.length} \u4E2A\u9519\u8BEF`);
      if (errors.length <= 3) {
        new import_obsidian.Notice(errors.join("\n"), 8e3);
      } else {
        new import_obsidian.Notice(`\u540C\u6B65\u5B8C\u6210\uFF0C\u4F46\u5B58\u5728 ${errors.length} \u4E2A\u9519\u8BEF`, 8e3);
      }
    }
    await this.logger.flush();
    this.reportProgress(completed, total, "\u540C\u6B65\u5B8C\u6210");
    return { postUploadEtags, postDownloadMtimes };
  }
  /**
   * 更新文件状态
   */
  async updateStates(uploadPaths, downloadPaths, deleteRemotePaths, deleteLocalPaths, conflictPaths, localFiles, remoteFiles, postUploadEtags, postDownloadMtimes) {
    const localMap = new Map(localFiles.map((f) => [f.path, f]));
    const remoteMap = new Map(remoteFiles.map((f) => [f.path, f]));
    for (const path of uploadPaths) {
      const lf = localMap.get(path);
      const realEtag = postUploadEtags.get(path);
      this.tracker.setState(path, {
        localMtime: lf?.mtime || 0,
        localHash: lf?.hash || "",
        remoteMtime: null,
        remoteHash: realEtag || null,
        status: "synced"
      });
    }
    for (const path of downloadPaths) {
      const realMtime = postDownloadMtimes.get(path);
      let realHash = "";
      try {
        const content = await this.vault.adapter.read(path);
        realHash = await computeHash(content);
      } catch (err) {
        this.logger.warn(`\u91CD\u65B0\u8BA1\u7B97\u4E0B\u8F7D\u6587\u4EF6 hash \u5931\u8D25 ${path}: ${err}`);
      }
      const rf = remoteMap.get(path);
      this.tracker.setState(path, {
        localMtime: realMtime || 0,
        localHash: realHash,
        remoteMtime: rf?.mtime || null,
        remoteHash: rf?.etag || null,
        status: "synced"
      });
    }
    for (const path of deleteRemotePaths) {
      this.tracker.removeState(path);
    }
    for (const path of deleteLocalPaths) {
      this.tracker.removeState(path);
    }
    for (const path of conflictPaths) {
      const lf = localMap.get(path);
      const rf = remoteMap.get(path);
      this.tracker.setState(path, {
        localMtime: lf?.mtime || 0,
        localHash: lf?.hash || "",
        remoteMtime: rf?.mtime || null,
        remoteHash: rf?.etag || null,
        status: "synced"
      });
    }
  }
};

// src/logger.ts
var LOG_DIR = ".obsidian/plugins/obsidian-webdav-sync";
var LOG_FILE = "sync.log";
var MAX_LINES = 500;
var Logger = class {
  constructor(vault) {
    this.logs = [];
    this.vault = vault;
  }
  /**
   * 写入一条日志
   */
  log(level, message) {
    const timestamp = new Date().toLocaleString("zh-CN", { hour12: false });
    const line = `[${timestamp}] [${level}] ${message}`;
    this.logs.push(line);
    if (level === "ERROR") {
      console.error(line);
    } else if (level === "WARN") {
      console.warn(line);
    } else {
      console.log(line);
    }
  }
  info(msg) {
    this.log("INFO", msg);
  }
  warn(msg) {
    this.log("WARN", msg);
  }
  error(msg) {
    this.log("ERROR", msg);
  }
  /**
   * 将所有日志写入文件（追加模式）
   */
  async flush() {
    if (this.logs.length === 0)
      return;
    try {
      await this.vault.adapter.mkdir(LOG_DIR);
      let existing = "";
      try {
        existing = await this.vault.adapter.read(`${LOG_DIR}/${LOG_FILE}`);
      } catch {
      }
      const allLines = existing ? existing.split("\n") : [];
      const newLines = this.logs;
      const merged = [...allLines, ...newLines];
      if (merged.length > MAX_LINES) {
        merged.splice(0, merged.length - MAX_LINES);
      }
      await this.vault.adapter.write(`${LOG_DIR}/${LOG_FILE}`, merged.join("\n") + "\n");
      this.logs = [];
    } catch (err) {
      console.error("\u5199\u5165\u65E5\u5FD7\u6587\u4EF6\u5931\u8D25:", err);
    }
  }
  /**
   * 获取日志文件路径（供设置界面显示"查看日志"用）
   */
  getLogFilePath() {
    return `${LOG_DIR}/${LOG_FILE}`;
  }
};

// src/settings.ts
var import_obsidian2 = require("obsidian");
var WebdavSyncSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h3", { text: "\u{1F4CA} \u64CD\u4F5C" });
    new import_obsidian2.Setting(containerEl).setName("\u7ACB\u5373\u540C\u6B65").setDesc("\u7ACB\u5373\u5F00\u59CB\u540C\u6B65\u672C\u5730\u6587\u4EF6\u4E0E WebDAV \u670D\u52A1\u5668").addButton(
      (btn) => btn.setButtonText("\u{1F504} \u7ACB\u5373\u540C\u6B65").setCta().onClick(async () => {
        btn.setButtonText("\u540C\u6B65\u4E2D...");
        btn.setDisabled(true);
        try {
          const result = await this.plugin.runSync();
          btn.setButtonText(result.message);
        } catch {
          btn.setButtonText("\u540C\u6B65\u5931\u8D25");
        }
        setTimeout(() => {
          btn.setButtonText("\u{1F504} \u7ACB\u5373\u540C\u6B65");
          btn.setDisabled(false);
        }, 5e3);
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u6D4B\u8BD5\u8FDE\u63A5").setDesc("\u68C0\u67E5 WebDAV \u670D\u52A1\u5668\u662F\u5426\u53EF\u8BBF\u95EE").addButton(
      (btn) => btn.setButtonText("\u{1F504} \u6D4B\u8BD5\u8FDE\u63A5").onClick(async () => {
        btn.setButtonText("\u8FDE\u63A5\u4E2D...");
        btn.setDisabled(true);
        try {
          const result = await this.plugin.testConnection();
          if (result.ok) {
            btn.setButtonText("\u2705 \u8FDE\u63A5\u6210\u529F");
          } else {
            btn.setButtonText("\u274C " + result.message);
          }
        } catch {
          btn.setButtonText("\u274C \u8FDE\u63A5\u5931\u8D25");
        }
        setTimeout(() => {
          btn.setButtonText("\u{1F504} \u6D4B\u8BD5\u8FDE\u63A5");
          btn.setDisabled(false);
        }, 3e3);
      })
    );
    containerEl.createEl("h3", { text: "\u{1F517} WebDAV \u670D\u52A1\u5668" });
    new import_obsidian2.Setting(containerEl).setName("\u670D\u52A1\u5668\u5730\u5740").setDesc("WebDAV \u670D\u52A1\u7684\u5B8C\u6574 URL\uFF0C\u4F8B\u5982 https://example.com/webdav/").addText(
      (text) => text.setPlaceholder("https://example.com/webdav/").setValue(this.plugin.settings.webdavUrl).onChange(async (value) => {
        this.plugin.settings.webdavUrl = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u7528\u6237\u540D").addText(
      (text) => text.setPlaceholder("\u7528\u6237\u540D").setValue(this.plugin.settings.username).onChange(async (value) => {
        this.plugin.settings.username = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u5BC6\u7801").addText((text) => {
      text.setPlaceholder("\u5BC6\u7801").setValue(this.plugin.settings.password).onChange(async (value) => {
        this.plugin.settings.password = value;
        await this.plugin.saveSettings();
      });
      text.inputEl.type = "password";
    });
    containerEl.createEl("h3", { text: "\u23F1\uFE0F \u89E6\u53D1\u65B9\u5F0F" });
    new import_obsidian2.Setting(containerEl).setName("\u542F\u52A8\u65F6\u81EA\u52A8\u540C\u6B65").setDesc("Obsidian \u6253\u5F00\u540E\u81EA\u52A8\u89E6\u53D1\u540C\u6B65").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.syncOnStartup).onChange(async (value) => {
        this.plugin.settings.syncOnStartup = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u4FDD\u5B58\u65F6\u81EA\u52A8\u540C\u6B65").setDesc("\u6BCF\u6B21\u4FDD\u5B58\u6587\u4EF6\u65F6\u81EA\u52A8\u540C\u6B65\u8BE5\u6587\u4EF6").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.syncOnSave).onChange(async (value) => {
        this.plugin.settings.syncOnSave = value;
        await this.plugin.saveSettings();
        this.plugin.updateSaveSyncListener();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u5B9A\u65F6\u540C\u6B65").setDesc("\u6BCF\u9694\u6307\u5B9A\u5206\u949F\u6570\u81EA\u52A8\u540C\u6B65\uFF080 \u8868\u793A\u7981\u7528\uFF09").addText(
      (text) => text.setValue(String(this.plugin.settings.syncInterval)).onChange(async (value) => {
        const num = parseInt(value);
        if (!isNaN(num) && num >= 0) {
          this.plugin.settings.syncInterval = num;
          await this.plugin.saveSettings();
          this.plugin.updateIntervalSync();
        }
      })
    );
    containerEl.createEl("h3", { text: "\u2195\uFE0F \u540C\u6B65\u9009\u9879" });
    new import_obsidian2.Setting(containerEl).setName("\u540C\u6B65\u65B9\u5411").addDropdown(
      (dropdown) => dropdown.addOption("bidirectional", "\u53CC\u5411\u540C\u6B65\uFF08\u672C\u5730 \u2194 \u8FDC\u7A0B\uFF09").addOption("upload_only", "\u4EC5\u4E0A\u4F20\uFF08\u672C\u5730 \u2192 \u8FDC\u7A0B\uFF09").addOption("download_only", "\u4EC5\u4E0B\u8F7D\uFF08\u8FDC\u7A0B \u2192 \u672C\u5730\uFF09").setValue(this.plugin.settings.syncDirection).onChange(async (value) => {
        this.plugin.settings.syncDirection = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "\u{1F50D} \u6587\u4EF6\u8FC7\u6EE4" });
    new import_obsidian2.Setting(containerEl).setName("\u4EC5\u5305\u542B\u6A21\u5F0F").setDesc("\u4E00\u884C\u4E00\u4E2A glob \u6A21\u5F0F\uFF0C\u7559\u7A7A\u8868\u793A\u5305\u542B\u6240\u6709\u6587\u4EF6").addTextArea(
      (text) => text.setPlaceholder("*.md\n*.txt\nassets/**").setValue(this.plugin.settings.includePatterns).onChange(async (value) => {
        this.plugin.settings.includePatterns = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u6392\u9664\u6A21\u5F0F").setDesc("\u4E00\u884C\u4E00\u4E2A glob \u6A21\u5F0F\u3002.obsidian/ \u59CB\u7EC8\u88AB\u6392\u9664").addTextArea(
      (text) => text.setPlaceholder("archive/**\ntmp/**").setValue(this.plugin.settings.excludePatterns).onChange(async (value) => {
        this.plugin.settings.excludePatterns = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "\u26A1 \u51B2\u7A81\u5904\u7406" });
    new import_obsidian2.Setting(containerEl).setName("\u51B2\u7A81\u7B56\u7565").setDesc("\u65B0\u6587\u4EF6\u8986\u76D6\u65E7\u6587\u4EF6\uFF0C\u65E7\u6587\u4EF6\u81EA\u52A8\u91CD\u547D\u540D\u52A0\u65F6\u95F4\u6233\u5907\u4EFD").addText(
      (text) => text.setValue("newer_wins\uFF08\u65B0\u6587\u4EF6\u4F18\u5148\uFF09").setDisabled(true)
    );
  }
};

// main.ts
var WebdavSyncPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.client = null;
    this.tracker = null;
    this.logger = null;
    this.engine = null;
    this.intervalId = null;
    this.saveSyncHandler = null;
    this.statusBarItem = null;
    this.ribbonIcon = null;
  }
  // ==================== 生命周期 ====================
  async onload() {
    await this.loadSettings();
    this.logger = new Logger(this.app.vault);
    this.logger.info("\u63D2\u4EF6\u5DF2\u52A0\u8F7D");
    this.tracker = new FileTracker(this.app.vault);
    await this.tracker.load();
    this.initClient();
    this.initEngine();
    this.addSettingTab(new WebdavSyncSettingTab(this.app, this));
    this.addCommand({
      id: "sync-now",
      name: "Sync with WebDAV",
      callback: () => this.runSync()
    });
    this.statusBarItem = this.addStatusBarItem();
    this.statusBarItem.setText("WebDAV: \u5C31\u7EEA");
    this.ribbonIcon = this.addRibbonIcon(
      "cloud",
      "WebDAV \u8BBE\u7F6E",
      () => {
        const setting = this.app.setting;
        if (setting) {
          setting.open();
          setting.openTabById("obsidian-webdav-sync");
        }
      }
    );
    this.moveRibbonToBottom();
    this.updateSaveSyncListener();
    this.updateIntervalSync();
    if (this.settings.syncOnStartup && this.client) {
      setTimeout(() => {
        this.runSync();
      }, 5e3);
    }
  }
  onunload() {
    if (this.intervalId !== null) {
      window.clearInterval(this.intervalId);
      this.intervalId = null;
    }
    if (this.saveSyncHandler) {
      this.app.vault.off("modify", this.saveSyncHandler);
      this.saveSyncHandler = null;
    }
    this.logger?.flush();
  }
  // ==================== 设置管理 ====================
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.initClient();
    this.initEngine();
  }
  // ==================== 客户端初始化 ====================
  initClient() {
    if (this.settings.webdavUrl && this.settings.username) {
      this.client = new WebdavClient(
        this.settings.webdavUrl,
        this.settings.username,
        this.settings.password
      );
    } else {
      this.client = null;
    }
  }
  initEngine() {
    if (!this.client || !this.tracker || !this.logger)
      return;
    const resolver = new ConflictResolver(this.app.vault, this.client);
    this.engine = new SyncEngine(
      this.app.vault,
      this.client,
      this.tracker,
      resolver,
      this.settings,
      this.logger
    );
    this.engine.setOnProgress((current, total, message) => {
      if (total > 0) {
        this.statusBarItem?.setText(`WebDAV: ${message} (${current}/${total})`);
      } else {
        this.statusBarItem?.setText(`WebDAV: ${message}`);
      }
    });
  }
  /**
   * 将 Ribbon 图标移到最底部（设置齿轮上方）
   */
  moveRibbonToBottom() {
    if (!this.ribbonIcon)
      return;
    const retry = (attempt) => {
      if (attempt > 15)
        return;
      const ribbon = document.querySelector(".workspace-ribbon");
      if (!ribbon || !this.ribbonIcon) {
        setTimeout(() => retry(attempt + 1), 300);
        return;
      }
      const icons = ribbon.querySelectorAll(".clickable-icon");
      const sidebar = ribbon.querySelector(".sidebar-actions");
      const pluginIcons = Array.from(icons).filter(
        (icon) => !sidebar?.contains(icon)
      );
      const lastPluginIcon = pluginIcons[pluginIcons.length - 1];
      if (lastPluginIcon && this.ribbonIcon !== lastPluginIcon) {
        lastPluginIcon.parentNode?.insertBefore(
          this.ribbonIcon,
          lastPluginIcon.nextSibling
        );
      }
    };
    retry(0);
  }
  // ==================== 同步触发 ====================
  /**
   * 测试 WebDAV 连接
   */
  async testConnection() {
    if (!this.client) {
      return { ok: false, message: "\u8BF7\u5148\u914D\u7F6E\u670D\u52A1\u5668\u5730\u5740\u548C\u7528\u6237\u540D" };
    }
    return await this.client.testConnection();
  }
  /**
   * 执行完整同步
   */
  async runSync() {
    if (!this.engine) {
      new import_obsidian3.Notice("\u8BF7\u5148\u5728\u8BBE\u7F6E\u4E2D\u914D\u7F6E WebDAV \u8FDE\u63A5");
      return { success: false, message: "\u8BF7\u5148\u914D\u7F6E\u8FDE\u63A5" };
    }
    if (this.engine.isSyncing()) {
      new import_obsidian3.Notice("\u540C\u6B65\u5DF2\u5728\u8FDB\u884C\u4E2D");
      return { success: false, message: "\u540C\u6B65\u5DF2\u5728\u8FDB\u884C\u4E2D" };
    }
    this.ribbonIcon?.addClass("syncing");
    this.statusBarItem?.setText("WebDAV: \u540C\u6B65\u4E2D...");
    const result = await this.engine.sync();
    this.ribbonIcon?.removeClass("syncing");
    if (result.success) {
      this.statusBarItem?.setText("WebDAV: \u5DF2\u540C\u6B65");
      if (result.actions.length > 0) {
        new import_obsidian3.Notice(result.message);
      }
    } else {
      this.statusBarItem?.setText("WebDAV: \u9519\u8BEF");
      new import_obsidian3.Notice("\u540C\u6B65\u5931\u8D25: " + result.message);
    }
    setTimeout(() => {
      this.statusBarItem?.setText("WebDAV: \u5C31\u7EEA");
    }, 5e3);
    return result;
  }
  /**
   * 更新保存时同步监听器
   */
  updateSaveSyncListener() {
    if (this.saveSyncHandler) {
      this.app.vault.off("modify", this.saveSyncHandler);
      this.saveSyncHandler = null;
    }
    if (this.settings.syncOnSave && this.engine) {
      let timeoutId = null;
      this.saveSyncHandler = async () => {
        if (timeoutId !== null) {
          window.clearTimeout(timeoutId);
        }
        timeoutId = window.setTimeout(async () => {
          await this.runSync();
        }, 1e3);
      };
      this.app.vault.on("modify", this.saveSyncHandler);
    }
  }
  /**
   * 更新定时同步
   */
  updateIntervalSync() {
    if (this.intervalId !== null) {
      window.clearInterval(this.intervalId);
      this.intervalId = null;
    }
    if (this.settings.syncInterval > 0 && this.engine) {
      this.intervalId = window.setInterval(
        () => this.runSync(),
        this.settings.syncInterval * 60 * 1e3
      );
    }
  }
};
